### ISSUE TITLE
nhentai API

### ISSUE THREAD

**Issue by Kadantte** [chuang861012/nhentai-api#1]
Any updates ? 'cause the official get shut down by nhentai...

**Comment by py7hon** [comment]
Try using [This](https://nhentai.api.lemonzdev.xyz/api)

**Comment by Kadantte** [comment]
Thank's , Is it here on Github i mean is it have an open source ?

**Comment by chuang861012** [comment]
Since nhentai is having bandwidth issues I might go e-hentai for hentai contents rather than scraping nhentai...

> Try using [This](https://nhentai.api.lemonzdev.xyz/api)

This looks great. Any docs or github page?

**Comment by py7hon** [comment]
> > Try using [This](https://nhentai.api.lemonzdev.xyz/api)
> 
> This looks great. Any docs or github page?

I think the API is the same as before and i use the api for [nHentai Mirror](https://nhent.ai)
